# Generated by Django 4.0 on 2025-01-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500)),
                ('type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='question_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='type_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_login_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('msg', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_video_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=350)),
                ('result', models.CharField(max_length=350)),
                ('dt', models.CharField(max_length=350)),
                ('tm', models.CharField(max_length=350)),
                ('result_caption', models.CharField(max_length=350)),
            ],
        ),
    ]
